NewsLetterAppMVC/NewsLetterAppMVC/Models/NewsLetter.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsLetterAppMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewsLetterEntities : DbContext
    {
        public NewsLetterEntities()
            : base("name=NewsLetterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SignUp> SignUps { get; set; }
    }
}

NewsLetterAppMVC/NewsLetterAppMVC/Models/NewsLetter.Designer.cs
// T4 code generation is enabled for model 'C:\Users\smith\Desktop\Basic_C-Sharp_Projects\NewsLetterAppMVC\NewsLetterAppMVC\Models\NewsLetter.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

NewsLetterAppMVC/NewsLetterAppMVC/Models/NewsLetter.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

NewsLetterAppMVC/NewsLetterAppMVC/Models/SignUp.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsLetterAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignUp
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> Removed { get; set; }
    }
}

NewsLetterAppMVC/NewsLetterAppMVC/ViewModels/SignUpVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NewsLetterAppMVC.ViewModels
{
    public class SignUpVM
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
    }
}

NewsLetterAppMVC/NewsLetterAppMVC/Controllers/AdminController.cs
using NewsLetterAppMVC.Models;
using NewsLetterAppMVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewsLetterAppMVC.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            using (NewsLetterEntities db = new NewsLetterEntities())
            {
                //var signups = db.SignUps.Where(x => x.Removed == null).ToList();
                var signups = (from c in db.SignUps
                               where c.Removed == null
                               select c).ToList();
                var signupVMs = new List<SignUpVM>();
                foreach (var signup in signups)
                {
                    var signupVM = new SignUpVM();
                    signupVM.Id = signup.Id;
                    signupVM.FirstName = signup.FirstName;
                    signupVM.LastName = signup.LastName;
                    signupVM.EmailAddress = signup.EmailAddress;
                    signupVMs.Add(signupVM);
                }
                return View(signupVMs);
            }
        }

        public ActionResult Unsubscribe(int Id)
        {
            using (NewsLetterEntities db = new NewsLetterEntities())
            {
                var signup = db.SignUps.Find(Id);
                signup.Removed = DateTime.Now;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

NewsLetterAppMVC/NewsLetterAppMVC/Controllers/HomeController.cs
using NewsLetterAppMVC.Models;
using NewsLetterAppMVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewsLetterAppMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignUp(string firstName, string lastName, string emailAddress)
        {
            if (string.IsNullOrEmpty(firstName) || string.IsNullOrEmpty(lastName) || string.IsNullOrEmpty(emailAddress))
            {
                return View("~/Views/Shared/Error.cshtml");
            }
            else
            {
                using (NewsLetterEntities db = new NewsLetterEntities())
                {
                    var signup = new SignUp();
                    signup.FirstName = firstName;
                    signup.LastName = lastName;
                    signup.EmailAddress = emailAddress;

                    db.SignUps.Add(signup);
                    db.SaveChanges();
                }
                
                return View("Success");
            }
        }
    }
}

NewsLetterAppMVC/NewsLetterAppMVC/Views/Admin/Index.cshtml
@using NewsLetterAppMVC.ViewModels
@model List<SignUpVM>

<div class="row no-gutters m-3">
    <div class="card col-sm-12 col-md-10 col-lg-6 mx-auto shadow">
        <div class="card-header text-center">
            <h5 class="m-0">Sign-Ups</h5>
        </div>
        <div class="card-body">
       @foreach (var signup in Model)
       {
           using (Html.BeginForm("Unsubscribe", "Admin", FormMethod.Post))
           {
              <input type="hidden" name="Id" value="@signup.Id" />
              <div class="row mb-3">
                    <div class="col-2">
                        @signup.FirstName
                    </div>
                    <div class="col">
                        @signup.LastName
                    </div>
                    <div class="col-4">
                        @signup.EmailAddress
                    </div>
                <div class="col">
                    <button type="submit" class="btn btn-danger btn-block">
                        Unsubscribe
                    </button>
                </div>
              </div>
           }

       }
        </div>
    </div>
</div>

NewsLetterAppMVC/NewsLetterAppMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NewsLetter</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>